### ISSUE TITLE
请问：OMD-C消息的messageHeader是 10字节还是20字节？

### ISSUE THREAD

**Issue by javalover123** [openvega/openomd#6]
看[定义文件](https://github.com/openvega/openomd/blob/ba4341666446532954452b1379ba42ecdac81823/openomd_handler/src/nar/resources/noarch/omdc-sbe.xml#L38)应该是 10字节，
[测试数据里面是 20字节呢？](https://github.com/openvega/openomd/blob/ba4341666446532954452b1379ba42ecdac81823/openomd_test/src/test/c/omdcparsertest.cpp#L76)

**Comment by openvega** [comment]
It has been quite a while and I believe the the messageHeader and packageHeader is not in use. Please refer to the struct defined in omddef.h instead.

**Comment by javalover123** [comment]
One message contains PktHdr and MsgHdr and Msg, is this right?
Is possible use pure Java decode the message? 
I use maven import failed, Could not find artifact io.github.openvega:openomd:nar:1.0.4 in central, the code is below.

`

    <dependency>
      <groupId>io.github.openvega</groupId>
      <artifactId>openomd</artifactId>
      <version>1.0.4</version>
      <type>nar</type>
    </dependency>
`

**Comment by openvega** [comment]
One message contains 1 PktHdr and 1+ MsgHdr and Msg.

Please use 1.0.3 for now i will deploy 1.0.4 later.

**Comment by openvega** [comment]
kindly reminder the sbe decoder is not 100% compatible with OMD protocol, I have a script and some checkin code to patch those parts. 
I am pretty sure you will need to do similar patch for sbe generated Java code.

**Comment by javalover123** [comment]
I checked [.sbeomdhack file](https://github.com/openvega/openomd/blob/master/openomd_handler/src/main/include/omdc_sbe/AggregateOrderBookUpdate.h.sbeomdhack) is the same without [.sbeomdhack file](https://github.com/openvega/openomd/blob/master/openomd_handler/src/main/include/omdc_sbe/AggregateOrderBookUpdate.h), may i need modify the sbeomdhack file? Could you give a document or some tips?

**Comment by javalover123** [comment]
Build unit test (mvn test) is in openomd_handler or openomd?
Then execute mvn install in the directory openomd?
I get some errors when build openomd_test on Ubuntu 20.04, could you give a help?

[INFO] --- nar-maven-plugin:3.5.2:nar-testCompile (default-nar-testCompile) @ openomd_test ---
[WARNING] No file matching pattern (libpthread.so) for library name "pthread" was found.
[WARNING] No file matching pattern (libdl.so) for library name "dl" was found.
[WARNING] No file matching pattern (libpcap.so) for library name "pcap" was found.
[WARNING] No file matching pattern (libgomp.so) for library name "gomp" was found.
[INFO] 4 total files to be compiled.
[INFO] Found 16 processors available
[INFO] Limited used processors to 4
[INFO]
Starting Core 0 with 1 source files...
[INFO]
Starting Core 1 with 1 source files...
[INFO]
Starting Core 2 with 1 source files...
[INFO]
Starting Core 3 with 1 source files...
[ERROR] In file included from /home/jlo/openomd/openomd_test/target/test-nar/openomd_handler-1.0.4-noarch/include/openomd/fulltick.h:2,
[ERROR] In file included from c/omdchandlertest.cpp:4:
[ERROR]                  from c/orderbooktest.cpp:2:
[ERROR] /home/jlo/openomd/openomd_test/target/test-nar/openomd_handler-1.0.4-noarch/include/openomd/pcaputil.h:3:10: fatal error: pcap.h: No such file or directory
[ERROR] /home/jlo/openomd/openomd_test/target/test-nar/openomd_handler-1.0.4-noarch/include/openomd/orderbookdef.h:7:10: fatal error: boost/container_hash/hash.hpp: No such file or directory
[ERROR]     3 | #include <pcap.h>
[ERROR]     7 | #include <boost/container_hash/hash.hpp>
[ERROR]       |          ^~~~~~~~
[ERROR]       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR] compilation terminated.
[ERROR] compilation terminated.

**Comment by openvega** [comment]
You should mvn install from project root

**Comment by openvega** [comment]
> I checked [.sbeomdhack file](https://github.com/openvega/openomd/blob/master/openomd_handler/src/main/include/omdc_sbe/AggregateOrderBookUpdate.h.sbeomdhack) is the same without [.sbeomdhack file](https://github.com/openvega/openomd/blob/master/openomd_handler/src/main/include/omdc_sbe/AggregateOrderBookUpdate.h), may i need modify the sbeomdhack file? Could you give a document or some tips?

There is a simple doc mentioned about sbe generation:
https://github.com/openvega/openomd#generate-sbe-messages

**Comment by javalover123** [comment]
Thanks, I resolved.
