### ISSUE TITLE
LiquidityProvider message shuoud be 30 bytes in test file?

### ISSUE THREAD

**Issue by javalover123** [openvega/openomd#8]
LiquidityProvider message shuoud be 30 bytes = 16(packet header) + 4(message header) + 4(securitycode) + 4(Sub decoder header) + 2(lpBrokerNumber)?

https://github.com/openvega/openomd/blob/ba4341666446532954452b1379ba42ecdac81823/openomd_test/src/test/c/omdcparsertest.cpp#L295

**Comment by openvega** [comment]
From Spec it is 10+2n
16 + 4 + 4 + 2 + 2

**Comment by javalover123** [comment]
BrokerQueue message is 188 bytes = 16(packet header) + 4(message header) + 4(securitycode) + 4(Sub decoder header) + 40(Sub items count) * 4( 2(item) + 1(itemType) + 1(filler) )

https://github.com/openvega/openomd/blob/ba4341666446532954452b1379ba42ecdac81823/openomd_test/src/test/c/omdcparsertest.cpp#L578

**Comment by openvega** [comment]
Yes it is 188 bytes in the unit test. maybe the multiline
